//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPOSDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GPOSEntities : DbContext
    {
        public GPOSEntities()
            : base("name=GPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_transection> customer_transection { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<order_packages> order_packages { get; set; }
        public virtual DbSet<order_return> order_return { get; set; }
        public virtual DbSet<order_return_items> order_return_items { get; set; }
        public virtual DbSet<order_return_packages> order_return_packages { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<package_items> package_items { get; set; }
        public virtual DbSet<purchase_history> purchase_history { get; set; }
        public virtual DbSet<user_branch> user_branch { get; set; }
    }
}
