//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPOSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.order_items = new HashSet<order_items>();
            this.order_return_items = new HashSet<order_return_items>();
            this.package_items = new HashSet<package_items>();
            this.purchase_history = new HashSet<purchase_history>();
        }
    
        public int bid { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string company { get; set; }
        public int qty { get; set; }
        public int retail_price { get; set; }
        public int original_price { get; set; }
        public int discount_price { get; set; }
        public System.DateTime lastsold { get; set; }
        public bool tag { get; set; }
        public bool isActive { get; set; }
        public string Barcode { get; set; }
    
        public virtual branch branch { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_return_items> order_return_items { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_items> package_items { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_history> purchase_history { protected get; set; }
    }
}
