//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPOSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_return()
        {
            this.order_return_items = new HashSet<order_return_items>();
            this.order_return_packages = new HashSet<order_return_packages>();
        }
    
        public int oid { get; set; }
        public string user_id { get; set; }
        public int id { get; set; }
        public System.DateTime dt { get; set; }
    
        public virtual AspNetUser AspNetUser { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_return_items> order_return_items { protected get; set; }
        public virtual order order { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_return_packages> order_return_packages { protected get; set; }
    }
}
