//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPOSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_return_items
    {
        public int orid { get; set; }
        public int item_id { get; set; }
        public int id { get; set; }
        public int qty { get; set; }
    
        public virtual item item { protected get; set; }
        public virtual order_return order_return { protected get; set; }
    }
}
