//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPOSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_items = new HashSet<order_items>();
            this.order_packages = new HashSet<order_packages>();
            this.order_return = new HashSet<order_return>();
        }
    
        public int cus_id { get; set; }
        public string user_id { get; set; }
        public int id { get; set; }
        public System.DateTime dt { get; set; }
        public int total_amount { get; set; }
        public int total_profit { get; set; }
        public int disc { get; set; }
        public int rcv { get; set; }
    
        public virtual AspNetUser AspNetUser { protected get; set; }
        public virtual customer customer { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_packages> order_packages { protected get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_return> order_return { protected get; set; }
    }
}
