//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPOSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_branch
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public int branch_id { get; set; }
    
        public virtual AspNetUser AspNetUser { protected get; set; }
        public virtual branch branch { protected get; set; }
    }
}
